# Generated by Django 5.2.6 on 2025-09-06 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hospital_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appointment",
            name="date",
        ),
        migrations.RemoveField(
            model_name="doctor",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="age",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="contact",
        ),
        migrations.AddField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="diagnosis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="dob",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="hospital_app.doctor",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="hospital_app.patient",
            ),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="specialization",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Pending", "Pending")],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="hospital_app.appointment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Treatment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treatment_description", models.TextField()),
                (
                    "medicine_prescribed",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="treatments",
                        to="hospital_app.appointment",
                    ),
                ),
            ],
        ),
    ]
